//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipesFinder_bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Start {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Start() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecipesFinder_bot.Resources.Start", typeof(Start).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /start.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! This bot allows you to cook something tasty (or not). .
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of available commands:.
        /// </summary>
        public static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /about - bot information;.
        /// </summary>
        public static string MessageCommandAbout {
            get {
                return ResourceManager.GetString("MessageCommandAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /id - you can finf some recipe by id;.
        /// </summary>
        public static string MessageCommandID {
            get {
                return ResourceManager.GetString("MessageCommandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ing - This command finds a whore by ingredient; shows a list of all the required ingredients.
        /// </summary>
        public static string MessageCommandIng {
            get {
                return ResourceManager.GetString("MessageCommandIng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ingredients - search by ingredient;.
        /// </summary>
        public static string MessageCommandRecipe {
            get {
                return ResourceManager.GetString("MessageCommandRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://delivio.by.
        /// </summary>
        public static string MessageDelivio {
            get {
                return ResourceManager.GetString("MessageDelivio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @koko_by_bot.
        /// </summary>
        public static string MessageKoko {
            get {
                return ResourceManager.GetString("MessageKoko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are too lazy to cook, then order:.
        /// </summary>
        public static string MessageLaziness {
            get {
                return ResourceManager.GetString("MessageLaziness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://menu-menu.by.
        /// </summary>
        public static string MessageMenu {
            get {
                return ResourceManager.GetString("MessageMenu", resourceCulture);
            }
        }
    }
}
